name: Build and Release shadowsocks-rust deb package

on:
  push:
    branches:
      - shadowsocks-rust-server
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        TZ: Asia/Shanghai
        GITHUB_REF_NAME: ${{ github.ref_name }} # Pass ref_name to the container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            bash \
            curl \
            build-essential \
            musl-dev \
            git \
            ruby \
            ruby-dev \
            perl \
            xz-utils
          gem install fpm
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . $HOME/.cargo/env
          rustup target add x86_64-unknown-linux-musl

      - name: Make ss-rust.sh executable
        run: |
          chmod +x ss-rust.sh

      - name: Execute shadowsocks-rust build script
        run: |
          bash ss-rust.sh

      - name: Debug staging directory
        run: |
          echo "STAGING_DIR contents:"
          ls -la "$(pwd)/shadowsocks-rust-server/usr/bin" || echo "usr/bin is empty or missing"
          ls -la "$(pwd)/shadowsocks-rust-server/script" || echo "script dir is empty or missing"

      - name: Package shadowsocks-rust with FPM
        run: |
          fpm -s dir -C shadowsocks-rust-server -t deb \
            -n "shadowsocks-rust-server" \
            -v "${{ github.ref_name }}" \
            -a "amd64" \
            -f \
            --exclude 'script' \
            --deb-systemd shadowsocks-rust-server/script/shadowsocks-rust.service \
            --deb-systemd shadowsocks-rust-server/script/shadowsocks-rust-server@.service \
            --deb-init shadowsocks-rust-server/script/shadowsocks-rust.init \
            --deb-default shadows Knowlesocks-rust-server/script/shadowsocks-rust.default \
            --after-install shadowsocks-rust-server/script/shadowsocks-rust.postinst

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
