name: Build and Release shadowsocks-rust deb package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
      env:
        TZ: Asia/Shanghai
        GITHUB_REF_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache \
            bash \
            git \
            ruby \
            ruby-dev \
            musl-dev \
            build-base \
            perl \
            xz \
            tar
          gem install fpm
          rustup target add x86_64-unknown-linux-musl

      - name: Make ss-rust.sh executable
        run: |
          chmod +x ss-rust.sh

      - name: Execute shadowsocks-rust build script
        run: |
          bash ss-rust.sh

      - name: Debug staging directory
        run: |
          echo "STAGING_DIR contents:"
          ls -la "$(pwd)/shadowsocks-rust-server" || echo "shadowsocks-rust-server is empty or missing"
          ls -la "$(pwd)/shadowsocks-rust-server/usr/bin" || echo "usr/bin is empty or missing"
          ls -la "$(pwd)/shadowsocks-rust-server/script" || echo "script dir is empty or missing"
          ls -la "$(pwd)/shadowsocks-rust-server/etc/shadowsocks-rust" || echo "etc/shadowsocks-rust is empty or missing"

      - name: Package shadowsocks-rust with FPM
        run: |
          VERSION="${GITHUB_REF_NAME#v}"  # Strip 'v' prefix
          fpm -s dir -C shadowsocks-rust-server -t deb \
            -n "shadowsocks-rust-server" \
            -v "$VERSION" \
            -a "amd64" \
            -f \
            --exclude 'script' \
            --deb-no-default-config-files \
            --verbose \
            $([ -f shadowsocks-rust-server/script/shadowsocks-rust.service ] && echo "--deb-systemd shadowsocks-rust-server/script/shadowsocks-rust.service") \
            $([ -f shadowsocks-rust-server/script/shadowsocks-rust.init ] && echo "--deb-init shadowsocks-rust-server/script/shadowsocks-rust.init") \
            $([ -f shadowsocks-rust-server/script/shadowsocks-rust.default ] && echo "--deb-default shadowsocks-rust-server/script/shadowsocks-rust.default") \
            $([ -f shadowsocks-rust-server/script/shadowsocks-rust.postinst ] && echo "--after-install shadowsocks-rust-server/script/shadowsocks-rust.postinst")
        shell: bash --noprofile --norc -e -o pipefail {0}

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
