name: Build and Release Nginx

on:
  push:
    branches:
      - main  # Adjust as needed
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:alpine
      env:
        TZ: Asia/Shanghai
      options: --privileged

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      # Install dependencies (bash, curl, build tools, and FPM)
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache bash curl alpine-sdk strip
          gem install fpm

      # Execute Nginx build script
      - name: Execute Nginx build script
        run: |
          set -eux
          bash nginx-ai.sh
        # Assumption: nginx-ai.sh builds Nginx and places it in /usr/sbin/nginx

      # Strip Nginx binary
      - name: Strip Nginx binary
        run: |
          strip /usr/sbin/nginx || echo "Strip failed, proceeding anyway"

      # Package Nginx as a Debian package with FPM
      - name: Package Nginx with FPM
        run: |
          mkdir -p package/usr/sbin
          cp /usr/sbin/nginx package/usr/sbin/
          fpm -s dir -t deb \
            -n "nginx-custom" \
            -v "${{ github.ref_name }}" \
            --description "Static Nginx build" \
            --maintainer "Your Name <your.email@example.com>" \
            -a all \
            -d "libc6" \
            package/

      # Upload release
      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')  # Only run on tags
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
