name: Build and Release Nginx deb packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:alpine
      env:
        TZ: Asia/Shanghai
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache bash curl alpine-sdk perl xz
          gem install fpm

      - name: Execute Nginx build script
        run: |
          set -eux
          export STAGING_DIR="$(pwd)/staging"
          bash nginx.sh
        # Removed env block since $(pwd) doesn't expand here

      - name: Debug staging directory
        run: |
          echo "STAGING_DIR contents:"
          ls -la "$(pwd)/staging/usr/sbin" || echo "Staging directory or usr/sbin is empty or missing"
          echo "Container root /usr/sbin contents:"
          ls -la /usr/sbin/nginx || echo "No nginx binary in /usr/sbin"

      - name: Strip Nginx binary
        run: |
          strip "$(pwd)/staging/usr/sbin/nginx" || echo "Strip failed, proceeding anyway"

      - name: Package Nginx with FPM
        run: |
          fpm -s dir -t deb \
            -n "nginx-custom" \
            -v "${{ github.ref_name }}" \
            --description "Custom Nginx build with LibreSSL and ngx-fancyindex" \
            --maintainer "Your Name <your.email@example.com>" \
            -a all \
            -d "musl" \
            --prefix / \
            "$(pwd)/staging/"

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
