name: Build and Release Nginx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ruby:alpine
      env:
        TZ: Asia/Shanghai
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: install bash
      run: |
       apk --update add bash
       apk add curl
        
    - name: Execute Nginx build script
      run: |
        set -eux  
        bash nginx-ai.sh
        

    - name: Strip Nginx binary
      run: strip /usr/sbin/nginx

    

    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
       tag_name: ${{ github.ref_name }}
       files: |
           /usr/sbin/nginx
      
